# Generated by Django 2.2 on 2019-04-22 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblPriceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_type', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='TblStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_desc', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='TblProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impression', models.IntegerField()),
                ('full_title', models.CharField(max_length=55)),
                ('isbn13', models.CharField(max_length=13)),
                ('tblstatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_tblstatus', to='costingapp.TblStatus')),
            ],
        ),
        migrations.CreateModel(
            name='TblPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tblpricetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_tblpricetype', to='costingapp.TblPriceType')),
                ('tblproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_tblproduct', to='costingapp.TblProduct')),
            ],
        ),
    ]
